export const Images = {
  onBoardingImageOne: require('../assets/images/onBoarding3.png'),
  onBoardingImageSecond: require('../assets/images/onBoarding2.png'),
  onBoardingImageThird: require('../assets/images/onBoarding1.png'),
  welcomeScreenIcon: require('../assets/icons/welcomeScreenIcon.png'),
  google: require('../assets/icons/search.png'),
  apple: require('../assets/icons/apple.png'),
  facebook: require('../assets/icons/facebook.png'),
  twitter: require('../assets/icons/twitter.png'),
  backIcon: require('../assets/icons/back.png'),
  Email: require('../assets/icons/mail.png'),
  password: require('../assets/icons/padlock.png'),
  ViewPassword: require('../assets/icons/view.png'),
  HidePassword: require('../assets/icons/hidden.png'),
  WelcomeScreenModalImage: require('../assets/images/welcomeModalImage.png'),
  passResetSuccess: require('../assets/images/passResetSuccess.png'),
  checkMark: require('../assets/images/checkMark.png'),
  phoneCall: require('../assets/icons/phone-call.png'),
  SignUpLastScreen: require('../assets/images/SignUpLastScreen.png'),
  imagePickIcon: require('../assets/icons/profile.png'),
  editIcon: require('../assets/icons/edit.png'),
  downArrow: require('../assets/icons/down-arrow.png'),
  calender: require('../assets/icons/calendar.png'),
  checkIcon: require('../assets/icons/check.png'),
};
