export const images = {
  takeOff: require('../assets/icons/departure.png'),
  landing: require('../assets/icons/landing.png'),
  TabHomeIcon: require('../assets/icons/hut.png'),
  saved : require('../assets/icons/bookmark.png'),
  booking : require('../assets/icons/tickets.png'),
  wallet : require('../assets/icons/wallet.png'),
  account : require('../assets/icons/user.png'),
  calendar : require('../assets/icons/calendar.png'),
  demoPic : require('../assets/images/demoPic.png'),
  bell : require('../assets/icons/notification.png'),
  seat : require('../assets/icons/car-seat.png'),
  passenger : require('../assets/icons/people.png'),
  forward : require('../assets/icons/skip-track.png'),
  up_down : require('../assets/icons/up-and-down.png'),
  cancel : require('../assets/icons/close.png'),
  search : require('../assets/icons/Search.png'),
  adult : require('../assets/icons/man.png'),
  children : require('../assets/icons/children.png'),
  twoYearBelowChild : require('../assets/icons/baby-boy.png'),
  tickMark : require('../assets/icons/check.png'),
};
