export const Images = {
  takeOff: require('../assets/icons/departure.png'),
  landing: require('../assets/icons/landing.png'),
  TabHomeIcon: require('../assets/icons/hut.png'),
  saved: require('../assets/icons/bookmark.png'),
  booking: require('../assets/icons/tickets.png'),
  wallet: require('../assets/icons/wallet.png'),
  account: require('../assets/icons/user.png'),
  calendar: require('../assets/icons/calendar.png'),
  demoPic: require('../assets/images/demoPic.png'),
  bell: require('../assets/icons/notification.png'),
  seat: require('../assets/icons/car-seat.png'),
  passenger: require('../assets/icons/people.png'),
  forward: require('../assets/icons/skip-track.png'),
  up_down: require('../assets/icons/up-and-down.png'),
  // tabHomeIcon: require('../assets/icons/Home.png'),
  // tabActiveHomeIcon: require('../assets/icons/ActiveHome.png'),
  backIcon: require('../assets/icons/back.png'),
  menuIcon: require('../assets/icons/menu.png'),
  airplaneBlueIcon: require('../assets/icons/airplaneBlue.png'),
  airplaneWhiteIcon: require('../assets/icons/airplaneWhite.png'),
  airplaneGreIcon: require('../assets/icons/airplaneGre.png'),
  filterIcon: require('../assets/icons/filter.png'),
  sortIcon: require('../assets/icons/sort.png'),
  shareIcon: require('../assets/icons/share.png'),
};
